public class Calculator {
    public void printNewMessage(String msg){
        system.debug(msg);
    }
    public string printAndReturnMessage(string msg){
        string returnStr = msg + '....OK coll';
        return returnStr;
    }
    public integer add(integer a,integer b){
        integer sum=a+b;  
        return sum;
    }
    public integer add(integer i, Integer j, Integer k){
        integer sum = i+j+k;
        return sum;
    }
}
